#
# GRAKN.AI - THE KNOWLEDGE GRAPH
# Copyright (C) 2018 Grakn Labs Ltd
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: 2.1
commands:
  install-bazel-linux-rbe:
    steps:
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-linux.sh
      - run: bash ./install-bazel-linux.sh && rm ./install-bazel-linux.sh
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-rbe.sh
      - run: bash ./install-bazel-rbe.sh && rm ./install-bazel-rbe.sh

  install-bazel-mac:
    steps:
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-mac.sh
      - run: bash ./install-bazel-mac.sh && rm ./install-bazel-mac.sh

  install-linux-dependencies:
    steps:
      - run: sudo apt install xvfb libxtst6 libxss1 libgtk2.0-0 libnss3 libasound2 libgconf-2-4 -y
      - run: Xvfb :99 & export DISPLAY=:99

  run-bazel-rbe:
    parameters:
      command:
        type: string
    steps:
      - run: bazel run @graknlabs_build_tools//ci:run-bazel-rbe -- << parameters.command >>

  run-grakn-server-linux:
    steps:
      - run-bazel-rbe:
          command: bazel build @graknlabs_grakn_core//:assemble-linux-targz
      - run: mkdir -p dist && tar -xvzf bazel-genfiles/external/graknlabs_grakn_core/grakn-core-all-linux.tar.gz -C ./dist/
      - run: nohup ./dist/grakn-core-all-linux/grakn server start

  run-grakn-server-mac:
    steps:
      - run: bazel build @graknlabs_grakn_core//:assemble-mac-zip
      - run: unzip bazel-genfiles/external/graknlabs_grakn_core/grakn-core-all-mac.zip -d ./dist/
      - run: nohup ./dist/grakn-core-all-mac/grakn server start

jobs:
  test-linux:
    machine: true
    working_directory: ~/workbase
    steps:
      - install-linux-dependencies
      - install-bazel-linux-rbe
      - checkout
      - run-grakn-server-linux
      - run: ./dist/grakn-core-all-linux/grakn console -f `pwd`/test/helpers/basic-genealogy.gql -k gene
      - run: bazel run @nodejs//:npm install
      - run: bazel run @nodejs//:npm run unit
      - run: bazel run @nodejs//:npm run integration
      # - run: bazel run @nodejs//:npm run e2e

  test-mac:
    macos:
      xcode: "9.0"
    working_directory: ~/workbase
    steps:
      - checkout
      - install-bazel-mac
      - run-grakn-server-mac
      - run: ./dist/grakn-core-all-mac/grakn console -f `pwd`/test/helpers/basic-genealogy.gql -k gene
      - run: bazel run @nodejs//:npm install
      - run: bazel run @nodejs//:npm run unit
      - run: bazel run @nodejs//:npm run integration
      # - run: bazel run @nodejs//:npm run e2e

  assemble-linux:
    machine: true
    working_directory: ~/workbase
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: bazel run @nodejs//:npm install
      - run: bazel run @nodejs//:npm run build
      - run: mkdir -p ~/distribution && mv ./build/*.tar.gz ~/distribution/grakn-workbase-linux-$(cat VERSION).tar.gz
      - persist_to_workspace:
          root: ~/distribution
          paths:
            - ./*

  assemble-mac:
    macos:
      xcode: "9.0"
    working_directory: ~/workbase
    steps:
      - install-bazel-mac
      - checkout
      - run: bazel run @nodejs//:npm install
      - run: |
          export CSC_LINK="$APPLE_CODE_SIGNING_CERTIFICATE_URL"
          export CSC_KEY_PASSWORD="$APPLE_CODE_SIGNING_PASSWORD"
          bazel run @nodejs//:npm run build
      - run: mkdir -p ~/distribution && mv ./build/*.dmg ~/distribution/grakn-workbase-mac-$(cat VERSION).dmg
      - persist_to_workspace:
          root: ~/distribution
          paths:
            - ./*

  assemble-windows:
    machine: true
    working_directory: ~/workbase
    steps:
      - checkout
      - run:
          command: .circleci/windows/assemble.py grakn-workbase-windows-$(cat VERSION).exe
          no_output_timeout: 30m
      - run: mkdir -p ~/distribution && mv ./grakn-workbase-windows-$(cat VERSION).exe ~/distribution/
      - persist_to_workspace:
          root: ~/distribution
          paths:
            - ./*

  cache-distribution:
    machine: true
    working_directory: ~/workbase
    steps:
      - attach_workspace:
          at: ~/distribution
      - restore_cache:
          key: distribution-{{ .Environment.CIRCLE_SHA1 }}
      - run: |
          if [ "$(ls -A ~/cache)" ]; then
            ls ~/cache/
            mkdir -p ~/distribution
            cp ~/cache/* ~/distribution/
          else
            ls ~/distribution
            mkdir -p ~/cache
            cp ~/distribution/* ~/cache/
          fi
      - save_cache:
          key: distribution-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/cache
      - persist_to_workspace:
          root: ~/distribution
          paths:
            - ./*

  release-approval:
    machine: true
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: |
          export RELEASE_APPROVAL_TOKEN=$REPO_GITHUB_TOKEN_GRABL
          bazel run @graknlabs_build_tools//ci:release-approval

  deploy-github:
    docker:
      - image: cibuilds/github:0.10
    working_directory: ~/workbase
    steps:
      - attach_workspace:
          at: ~/distribution
      - checkout
      - run:
          name: "Publish Draft Release on GitHub"
          command: |
            ghr -t ${REPO_GITHUB_TOKEN_GRABL} -u ${CIRCLE_PROJECT_USERNAME} \
            -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} \
            -delete -draft $(cat VERSION) ~/distribution/

  deploy-brew-release:
    machine: true
    working_directory: ~/workbase
    steps:
      - attach_workspace:
          at: ~/distribution
      - install-bazel-linux-rbe
      - checkout
      - run: cp ~/distribution/grakn-workbase-mac-$(cat VERSION).dmg ~/workbase/
      - run:
          command: |
            export DEPLOY_BREW_TOKEN=$REPO_GITHUB_TOKEN_GRABL
            export DEPLOY_BREW_CHECKSUM=$(sha256sum grakn-workbase-mac-$(cat VERSION).dmg | awk '{print $1}')
            bazel run //:deploy-brew -- release

  release-cleanup:
    machine: true
    steps:
      - checkout
      - run: git push --delete origin workbase-release-branch

workflows:
  workbase:
    jobs:
      - test-linux:
          filters:
            branches:
              ignore: workbase-release-branch
      - test-mac:
          filters:
            branches:
              ignore: workbase-release-branch
      - assemble-linux:
          filters:
            branches:
              only: master
          requires:
            - test-linux
            - test-mac
      - assemble-mac:
          filters:
            branches:
              only: master
          requires:
            - test-linux
            - test-mac
      - assemble-windows:
          filters:
            branches:
              only: master
      - cache-distribution:
          filters:
            branches:
              only: master
          requires:
            - assemble-linux
            - assemble-mac
            - assemble-windows
      - release-approval:
          filters:
            branches:
              only: master
          requires:
            - cache-distribution

  workbase-release:
    jobs:
      - cache-distribution:
          filters:
            branches:
              only: workbase-release-branch
      - deploy-github:
          filters:
            branches:
              only: workbase-release-branch
          requires:
            - cache-distribution
      - deploy-approval:
          type: approval
          filters:
            branches:
              only: workbase-release-branch
          requires:
            - deploy-github
      - deploy-brew-release:
          filters:
            branches:
              only: workbase-release-branch
          requires:
            - deploy-approval
      - release-cleanup:
          filters:
            branches:
              only: workbase-release-branch
          requires:
            - deploy-brew-release
