version: 2.1
commands:
  bazel_install:
    steps:
      - run:
          name: Bazel - Install
          command: |
            curl -OL https://github.com/bazelbuild/bazel/releases/download/0.20.0/bazel-0.20.0-installer-linux-x86_64.sh
            chmod +x bazel-0.20.0-installer-linux-x86_64.sh
            sudo ./bazel-0.20.0-installer-linux-x86_64.sh

  bazel-install-macos:
    steps:
      - run:
          name: Bazel - Install (macOS)
          command: |
            curl -OL https://github.com/bazelbuild/bazel/releases/download/0.20.0/bazel-0.20.0-installer-darwin-x86_64.sh
            chmod +x bazel-0.20.0-installer-darwin-x86_64.sh
            sudo ./bazel-0.20.0-installer-darwin-x86_64.sh

  bazel_add_rbe_credential:
    steps:
      - run:
          name: Bazel - Add RBE Credential
          command: |
            if [[ -n "$BAZEL_RBE_CREDENTIAL" ]]; then
              BAZEL_RBE_CREDENTIAL_LOCATION=~/.config/gcloud/application_default_credentials.json
              echo "An RBE credential is found and will be saved to $BAZEL_RBE_CREDENTIAL_LOCATION. Bazel will be executed with RBE support."
              mkdir -p ~/.config/gcloud/
              echo $BAZEL_RBE_CREDENTIAL > "$BAZEL_RBE_CREDENTIAL_LOCATION"
            else
              echo "No RBE credential found. Bazel will be executed locally without RBE support."
            fi

  run-grakn-server:
    parameters:
      rbe:
        description: use RBE while building
        type: boolean
        default: false
    steps:
      - run: bazel build @graknlabs_grakn_core//:distribution <<# rbe >> --config=rbe <</ rbe >>
      - run: unzip bazel-genfiles/external/graknlabs_grakn_core/grakn-core-all.zip -d bazel-genfiles/dist/
      - run: nohup bazel-genfiles/dist/grakn-core-all/grakn server start
      - run: bash bazel-genfiles/dist/grakn-core-all/grakn console -f `pwd`/test/helpers/basic-genealogy.gql -k gene

jobs:
  approve-release:
    machine: true
    steps:
      - checkout
      - run: python .circleci/approve-release.py

  release-cleanup:
    machine: true
    steps:
      - checkout
      - run: git push --delete origin trigger-ci-release


  build-workbase-win:
    machine: true
    working_directory: ~/grakn
    steps:
      - attach_workspace:
          at: ~/grakn
      - checkout
      - run:
          command: .circleci/build-workbase-win/build-workbase-win.py
          no_output_timeout: 20m

  build-workbase-linux:
    machine: true
    working_directory: ~/grakn
    steps:
      - attach_workspace:
          at: ~/grakn
      - checkout
      - bazel_install
      - bazel_add_rbe_credential
      - run-grakn-server:
          rbe: yes
      - run:
          name: npm install
          command: bazel run @nodejs//:npm install
      - run:
          name: npm run build
          command: bazel run @nodejs//:npm run build
      - run: mkdir -p ~/grakn/artifacts && mv ./build/*.tar.gz ~/grakn/artifacts/grakn-workbase-$(cat VERSION)-linux.tar.gz
      - persist_to_workspace:
          name: "Storing built Workbase"
          root: ~/grakn
          paths:
            - artifacts/*-linux.tar.gz
            - VERSION
      - run: sudo apt install xvfb libxtst6 libxss1 libgtk2.0-0 libnss3 libasound2 libgconf-2-4 -y
      - run: Xvfb :99 &
      - run: export DISPLAY=:99
      - run: bazel run @nodejs//:npm test
      - run: bazel run @nodejs//:npm run e2e

  build-workbase-mac:
    macos:
        xcode: "9.0"
    working_directory: ~/grakn
    steps:
      - attach_workspace:
          at: ~/grakn
      - checkout
      - bazel-install-macos
      - run-grakn-server
      - run:
          name: npm install
          command: bazel run @nodejs//:npm install
      - run: CSC_LINK="$APPLE_CODE_SIGNING_CERTIFICATE_URL" CSC_KEY_PASSWORD="$APPLE_CODE_SIGNING_PASSWORD" bazel run @nodejs//:npm run build
      - run: bazel run @nodejs//:npm run unit
      - run: bazel run @nodejs//:npm run e2e
      - run: mkdir -p ~/grakn/artifacts && mv ./build/*.zip ~/grakn/artifacts/grakn-workbase-$(cat VERSION)-mac.zip
      - persist_to_workspace:
          root: ~/grakn
          paths:
            - artifacts/*-mac.zip
  publish-github-draft:
    docker:
      - image: cibuilds/github:0.10
    working_directory: ~/grakn
    steps:
      - attach_workspace:
          at: ~/grakn
      - run:
          name: "Publish Draft Release on GitHub"
          command: |
            ghr -t ${GRABL_CREDENTIAL} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete -draft v$(cat VERSION) ./artifacts


workflows:
  version: 2
  ci-pull-request:
    jobs:
      - build-workbase-linux:
          filters:
            branches:
              ignore: /master|trigger-ci-release/
      - build-workbase-mac:
          filters:
            branches:
              ignore: /master|trigger-ci-release/
      - build-workbase-win:
          filters:
            branches:
              ignore: /master|trigger-ci-release/
  ci-master-branch:
    jobs:
      - build-workbase-linux:
          filters:
            branches:
              only: master
      - build-workbase-mac:
          filters:
            branches:
              only: master
      - build-workbase-win:
          filters:
            branches:
              only: master
      - approve-release:
          requires:
            - build-workbase-linux
            - build-workbase-mac
            - build-workbase-win
          filters:
            branches:
              only: master
  ci-release:
    jobs:
      - build-workbase-linux:
          filters:
            branches:
              only: trigger-ci-release
      - build-workbase-mac:
          filters:
            branches:
              only: trigger-ci-release
      - build-workbase-win:
          filters:
            branches:
              only: trigger-ci-release
      - publish-github-draft:
          requires:
            - build-workbase-linux
            - build-workbase-mac
            - build-workbase-win
          filters:
            branches:
              only: trigger-ci-release
      - release-cleanup:
          requires:
            - publish-github-draft
          filters:
            branches:
              only: trigger-ci-release
