#
# Copyright (C) 2021 Grakn Labs
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: 2.1
orbs:
  win: circleci/windows@2.0.0
commands:

  install-bazel-mac:
    steps:
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/dependencies/master/tool/bazelinstall/mac.sh
      - run: bash ./mac.sh && rm ./mac.sh

  run-bazel:
    parameters:
      command:
        type: string
    steps:
      - run:
          command: bazel run @graknlabs_dependencies//tool/bazelrun:rbe -- << parameters.command >>
          no_output_timeout: 120m

jobs:
  deploy-mac:
    macos:
      xcode: "10.2.1"
    working_directory: ~/grakn
    steps:
      - install-bazel-mac
      - checkout
      - run: brew install nvm
      - run: mkdir ~/.nvm
      - run: echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.bash_profile
      - run: echo '[ -s "$(brew --prefix)/opt/nvm/nvm.sh" ] && . "$(brew --prefix)/opt/nvm/nvm.sh"' >> ~/.bash_profile
      - run: nvm install 15.11.0
      - run: nvm use 15.11.0
      - run: npm install
      - run: |
          export CSC_LINK=$APPLE_CODE_SIGNING_CERTIFICATE_URL
          export CSC_KEY_PASSWORD=$APPLE_CODE_SIGNING_PASSWORD
          npm run build
      - run: |
          export RELEASE_NOTES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @graknlabs_dependencies//tool/release:create-notes -- workbase $(cat VERSION) ./RELEASE_TEMPLATE.md
          export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
          bazel run //:deploy-github-mac $CIRCLE_SHA1

  deploy-windows:
    executor:
      name: win/default
      shell: cmd.exe
    working_directory: ~/grakn
    steps:
      - checkout
      - run: .circleci\windows\prepare.bat
      - run: nvm install 15.11.0
      - run: nvm use 15.11.0
      - run: npm install
      - run: npm run build
      - run: .circleci\windows\deploy.bat

workflows:
  grakn-core:
    jobs:
      - deploy-mac:
          filters:
            branches:
              only: workbase-release-mac-windows-branch
      - deploy-windows:
          filters:
            branches:
              only: workbase-release-mac-windows-branch
