#
# Copyright (C) 2021 Grakn Labs
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

config:
  version-candidate: VERSION

build:
  correctness:
    build:
      image: graknlabs-ubuntu-20.04
      command: |
        bazel run @graknlabs_dependencies//tool/checkstyle:test-coverage
        bazel test $(bazel query 'kind(checkstyle_test, //...)') --test_output=streamed

        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
        export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && hash -r
        nvm install 15.11.0
        nvm use 15.11.0
        npm install
        npm run build

release:
  filter:
    owner: graknlabs
    branch: master
  validation:
    validate-dependencies:
      image: graknlabs-ubuntu-20.04
      command: bazel test //:release-validate-deps --test_output=streamed
  deployment:
    deploy-github-mac-windows:
      image: graknlabs-ubuntu-20.04
      command: |
        git checkout -b workbase-release-mac-windows-branch
        git push -f origin workbase-release-mac-windows-branch
        pyenv install -s 3.6.10 && pyenv global 3.6.10 system && pip3 install requests
        bazel run //:wait-for-release -- $GRABL_OWNER $GRABL_REPO $(cat VERSION) grakn-workbase.dmg grakn-workbase.exe
    deploy-github-linux:
      image: graknlabs-ubuntu-20.04
      command: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
        export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && hash -r
        nvm install 15.11.0
        nvm use 15.11.0
        npm install
        npm run build

        pyenv install -s 3.6.10 && pyenv global 3.6.10 system && pip install certifi
        export RELEASE_NOTES_TOKEN=$REPO_GITHUB_TOKEN
        bazel run @graknlabs_dependencies//tool/release:create-notes -- workbase $(cat VERSION) ./RELEASE_TEMPLATE.md
        export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
        bazel run //:deploy-github-linux -- $GRABL_COMMIT
    deploy-brew:
      image: graknlabs-ubuntu-20.04
      dependencies: [deploy-github-mac-windows]
      command: |
        wget "https://github.com/${GRABL_OWNER}/${GRABL_REPO}/releases/download/${cat VERSION}/grakn-workbase.dmg"
        export DEPLOY_BREW_TOKEN=$REPO_GITHUB_TOKEN
        export DEPLOY_BREW_CHECKSUM=$(sha256sum grakn-workbase.dmg | awk '{print $1}')
        bazel run --define version=$(cat VERSION) //:deploy-brew -- release
